services :
    security.access.anonymous_voter.class:
        class: "Starkerxp\\UtilisateurBundle\\Services\\Voters\\AnonymousVoter"
        arguments: ["@security.authentication.trust_resolver"]
        public:     false
        tags:
           - { name: security.voter }
    utilisateur.popo:
        class: "Starkerxp\\UtilisateurBundle\\Services\\Domain\\Utilisateur\\UtilisateurPOPO"
