#################################
# AdministrationController
#################################
administration:
    path: /administration.html
    defaults: { _controller: StarkerxpEcommerceBundle:Administration:index }
    methods:  [GET]
    
#################################
# DefaultController
#################################
homepage:
    path: /
    defaults: { _controller: StarkerxpEcommerceBundle:Default:index }
    methods:  [GET]
        
faq:
    path: /faq.html
    defaults: { _controller: StarkerxpEcommerceBundle:Default:faq }
    methods:  [GET]
        
mentions_legales:
    defaults: { _controller: StarkerxpEcommerceBundle:Default:mentionsLegales }
    path: /mentions-legales.html
    methods:  [GET]
        
contact:
    defaults: { _controller: StarkerxpEcommerceBundle:Default:contact }
    path: /contact.html
    methods:  [GET]

#################################
# AdministrationMarquesController
#################################
liste_marques:
    path: /administration/marques/
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationMarques:index }
    methods:  [GET]

formulaire_creation_marque:
    path: /administration/marques/ajouter.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationMarques:create }
    methods:  [GET]

creation_marque:
    path: /administration/marques/ajouter.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationMarques:post }
    methods:  [POST]

formulaire_modification_marque:
    path: /administration/marques/modifier/{marqueId}.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationMarques:edit }
    methods:  [GET]
    requirements:
        marqueId: "[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}"
        
modification_marque:
    path: /administration/marques/modifier/{marqueId}.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationMarques:put }
    methods:  [PUT]
    requirements:
        marqueId: "[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}"
        
suppression_marque:
    path: /administration/marques/supprimer/{marqueId}.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationMarques:delete }
    methods:  [DELETE]
    requirements:
        marqueId: "[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}"

#################################
# AdministrationProduitsController
#################################
liste_produits:
    path: /administration/produits/
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationProduits:index }
    methods:  [GET]

formulaire_creation_produit:
    path: /administration/produits/ajouter.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationProduits:create }
    methods:  [GET]

creation_produit:
    path: /administration/produits/ajouter.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationProduits:post }
    methods:  [POST]
    
formulaire_modification_produit:
    path: /administration/produits/modifier/{produitId}.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationProduits:edit }
    methods:  [GET]
    requirements:
        produitId: "[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}"
        
modification_produit:
    path: /administration/produits/modifier/{produitId}.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationProduits:put }
    methods:  [PUT]
    requirements:
        produitId: "[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}"
        
suppression_produit:
    path: /administration/produits/supprimer/{produitId}.html
    defaults: { _controller: StarkerxpEcommerceBundle:AdministrationProduits:delete }
    methods:  [DELETE]
    requirements:
        produitId: "[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}"
