services :
    # Bus
    bus.command.produit:
        class: "Starkerxp\\CQRSESBundle\\Services\\Command\\CommandBus"
        calls:
            - [register, ["@handler.command.creation_produit"]]
    bus.event.produit:
        class: "Starkerxp\\CQRSESBundle\\Services\\Query\\QueryBus"
        calls:
            - [register, ["@handler.query.lister_produit"]]
            - [register, ["@handler.query.get_produit"]]
    # Repository
    repository.read.produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Persistence\\Lecture\\Produit\\ProduitRepository"
        arguments: ["@doctrine.dbal.read_connection"]
    repository.write.produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Persistence\\Ecriture\\Produit\\ProduitRepository"
        arguments: ["@event_store", "@projection.produit"]
        
    # Projection
    projection.produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Persistence\\Ecriture\\Produit\\ProduitProjection"
        arguments: ["@doctrine.dbal.write_connection"]
        
    # Command
    handler.command.creation_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Command\\Produit\\CreerProduitHandler"
        arguments: ["@repository.write.produit"]

    # Query
    handler.query.lister_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Query\\Produit\\ProduitListerQueryHandler"
        arguments: ["@repository.read.produit"]
    handler.query.get_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Query\\Produit\\ProduitQueryHandler"
        arguments: ["@repository.read.produit"]