services :
    uploader.produits:
        class: "Starkerxp\\DocumentBundle\\Upload\\UploadService"
        arguments: ["@service_container", "uploads/produits"]
        
    # Bus
    bus.command.produit:
        class: "Starkerxp\\CQRSESBundle\\Services\\Command\\CommandBus"
        calls:
            - [register, ["@handler.command.creation_produit"]]
            - [register, ["@handler.command.modification_produit"]]
            - [register, ["@handler.command.supprimer_produit"]]
            - [register, ["@handler.command.supprimer_image_produit"]]
            
    bus.event.produit:
        class: "Starkerxp\\CQRSESBundle\\Services\\Query\\QueryBus"
        calls:
            - [register, ["@handler.query.lister_produit"]]
            - [register, ["@handler.query.get_produit"]]
            - [register, ["@handler.query.get_modifier_produit"]]
            - [register, ["@handler.query.get_image_produit_par_defaut"]]
            
    # Repository
    repository.read.produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Persistence\\Lecture\\ProduitRepository"
        arguments: ["@doctrine.dbal.read_connection", "@repository.read.marque" , "@repository.read.images_produit"]
    repository.read.images_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Persistence\\Lecture\\ImagesProduitRepository"
        arguments: ["@doctrine.dbal.read_connection"]
    repository.write.produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Persistence\\Ecriture\\Produit\\ProduitRepository"
        arguments: ["@event_store", "@projection.produit"]
        
    # Projection
    projection.produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Persistence\\Ecriture\\Produit\\ProduitProjection"
        arguments: ["@doctrine.dbal.write_connection"]
        
    # Query
    handler.query.lister_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Query\\Produit\\ProduitListerQueryHandler"
        arguments: ["@repository.read.produit"]
    handler.query.get_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Query\\Produit\\ProduitQueryHandler"
        arguments: ["@repository.read.produit"]
    handler.query.get_modifier_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Query\\Produit\\ModifierProduitQueryHandler"
        arguments: ["@repository.read.produit"]    
    handler.query.get_image_produit_par_defaut:
        class: "Starkerxp\\EcommerceBundle\\Services\\Query\\Produit\\ImageProduitParDefautQueryHandler"
        arguments: ["@repository.read.images_produit"]
        
    # Command
    handler.command.creation_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Command\\Produit\\CreerProduitHandler"
        arguments: ["@repository.write.produit"]
    handler.command.modification_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Command\\Produit\\ModifierProduitHandler"
        arguments: ["@repository.write.produit"]
    handler.command.supprimer_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Command\\Produit\\SupprimerProduitHandler"
        arguments: ["@repository.write.produit"]
    handler.command.supprimer_image_produit:
        class: "Starkerxp\\EcommerceBundle\\Services\\Command\\Produit\\SupprimerImageProduitHandler"
        arguments: ["@repository.write.produit", "@uploader.produits"]
        
    # Formulaire
    form.ajouter.produit:
        class: "Starkerxp\\EcommerceBundle\\Forms\\Produit\\CreationProduitForm"
        arguments: ["@repository.read.marque"]
    form.modifier.produit:
        class: "Starkerxp\\EcommerceBundle\\Forms\\Produit\\ModificationProduitForm"
        arguments: ["@repository.read.marque", "@repository.read.produit"]